# Generated by Django 5.2.8 on 2025-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='merchant_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('READY', 'Prêt pour ramassage'), ('PICKED_UP', 'Récupéré'), ('IN_TRANSIT', 'En cours de livraison'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
    ]
