# Generated by Django 5.2.8 on 2025-12-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Platform Fee', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10.00 for 10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='label',
            field=models.CharField(blank=True, choices=[('ORDER_PAYMENT', 'Paiement de commande'), ('MERCHANT_PAYOUT', 'Versement marchand'), ('COMMISSION', 'Commission plateforme'), ('WALLET_DEPOSIT', 'Rechargement portefeuille'), ('MANUAL_ADJUSTMENT', 'Ajustement manuel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('PAYMENT', 'Paiement'), ('REFUND', 'Remboursement'), ('TRANSFER', 'Transfert')], max_length=20),
        ),
    ]
