# Generated by Django 5.2.8 on 2025-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_dimensions_product_sku_product_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='DEFAULT', help_text='Stock Keeping Unit', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
